# en_match.py
"""
Translation dictionary for English (BASELINE).
Used as fallback when no language-specific translation exists.
"""

EN_TO_EN = {
    # From main.py
    "Error registering user. Please try again.": "Error registering user. Please try again.",
    "Please select an option from the menu.": "Please select an option from the menu.",
    "Invalid input. Please select an option from the menu.": "Invalid input. Please select an option from the menu.",
    "Invalid module. Returning to main menu.": "Invalid module. Returning to main menu.",
    "An error occurred. Please try again.": "An error occurred. Please try again.",
    "Language set to {}.": "Language set to {}.",

    # From utils.py
    "AnyHealth Bot": "AnyHealth Bot",
    "Welcome to AnyHealth Bot! Please choose an option:": "Welcome to AnyHealth Bot! Please choose an option:",
    "Select an option to proceed": "Select an option to proceed",
    "Menu": "Menu",
    "Main Options": "Main Options",
    "Notification": "Notification",
    "Booking": "Booking",
    "🌐Change Language": "🌐Change Language",
    "Booking Options": "Booking Options",
    "Booking Services": "Booking Services",
    "General GP Visit": "General GP Visit",
    "Checkup & Test": "Checkup & Test",
    "Vaccination": "Vaccination",
    "Report & Follow up": "Report & Follow up",
    "Report Result Booking": "Report Result Booking",
    "View Booking": "View Booking",
    "Reschedule Booking": "Reschedule Booking",
    "Hi, you have new notification(s), please tap on \"notification\" button in the Main Menu to check them out.": "Hi, you have new notification(s), please tap on \"notification\" button in the Main Menu to check them out.",
    "Invalid input. Please use the buttons provided.": "Invalid input. Please use the buttons provided.",

    # From calendar_utils.py - TITLES (≤24 chars)
    "Choose Doctor": "Choose Doctor",
    "Available Doctors": "Available Doctors",
    "Any Doctor": "Any Doctor",
    "Choose Date": "Choose Date",
    "Available Dates": "Available Dates",
    "Choose Hour": "Choose Hour",
    "Available Hours": "Available Hours",
    "Choose Slot": "Choose Slot",
    "30min Slots": "30min Slots",
    "Confirm": "Confirm",
    "Cancel": "Cancel",

    # From menu.py + main.py - TITLES (≤24 chars)
    "Select Language": "Select Language",
    "Languages": "Languages",
    "English": "English",
    "Bahasa Malaysia": "Bahasa Malaysia",
    "中文": "中文",
    "தமிழ்": "தமிழ்",

    # From calendar_utils.py - CONTENT
    "Select a doctor for your appointment or choose 'Any Doctor':": "Select a doctor for your appointment or choose 'Any Doctor':",
    "Select a date for your appointment:": "Select a date for your appointment:",
    "Select an hour for {}:": "Select an hour for {}:",
    "Select {}min slot for {} {}:": "Select {}min slot for {} {}:",
    "No doctors available. Please contact support.": "No doctors available. Please contact support.",
    "Unable to fetch doctors. Please try again.": "Unable to fetch doctors. Please try again.",
    "An error occurred while fetching doctors: {}. Please try again.": "An error occurred while fetching doctors: {}. Please try again.",
    "No available dates in the next 14 days. Please select another doctor.": "No available dates in the next 14 days. Please select another doctor.",
    "No available dates in the next 14 days. Please try again later.": "No available dates in the next 14 days. Please try again later.",
    "Unable to fetch calendar. Please try again.": "Unable to fetch calendar. Please try again.",
    "An error occurred while fetching the calendar: {}. Please try again.": "An error occurred while fetching the calendar: {}. Please try again.",
    "No available hours for this date. Please select another date.": "No available hours for this date. Please select another date.",
    "Unable to fetch hours. Please try again.": "Unable to fetch hours. Please try again.",
    "An error occurred while fetching hours: {}. Please try again.": "An error occurred while fetching hours: {}. Please try again.",
    "No available time slots.": "No available time slots.",
    "Error loading slots.": "Error loading slots.",
    "Selected time slot is no longer available. Please choose another.": "Selected time slot is no longer available. Please choose another.",
    "No doctors available for this time slot. Please select another.": "No doctors available for this time slot. Please select another.",
    "Confirm your booking:\n• Service: {}\n• Doctor: {}\n• Date: {}\n• Time: {}\n• Duration: {} min\n• Details: {}": "Confirm your booking:\n• Service: {}\n• Doctor: {}\n• Date: {}\n• Time: {}\n• Duration: {} min\n• Details: {}",
    "The booking is not placed": "The booking is not placed",

    # From menu.py + main.py - CONTENT
    "Please select your preferred language:": "Please select your preferred language:",
    "Choose a language to proceed": "Choose a language to proceed",
    "Error setting language. Please try again.": "Error setting language. Please try again.",
    "Invalid selection. Please try again.": "Invalid selection. Please try again.",
    "Invalid button selection. Please try again.": "Invalid button selection. Please try again.",

    # From utils.py - CONTENT
    "Please choose a booking option:": "Please choose a booking option:",

    # From notification.py
    "No notifications found.": "No notifications found.",
    "✅ {} notification(s) displayed!": "✅ {} notification(s) displayed!",

    # From view_booking.py - TITLES
    "View Booking Options": "View Booking Options",
    "View Past Consultations": "View Past Consultations",
    "View Upcoming Bookings": "View Upcoming Bookings",
    "Request Report": "Request Report",
    "Past Consultations": "Past Consultations",
    "Select Option": "Select Option",
    # CONTENT
    "You have no past consultations.": "You have no past consultations.",
    "Your past consultations:": "Your past consultations:",
    "Consultation with Dr. {} at {} on {} (Diagnosis: {})": "Consultation with Dr. {} at {} on {} (Diagnosis: {})",
    "Select a past consultation to request a report:": "Select a past consultation to request a report:",
    "Consultation {}": "Consultation {}",
    "User not found. Please ensure your number is registered.": "User not found. Please ensure your number is registered.",
    "Error fetching user information. Please try again.": "Error fetching user information. Please try again.",
    "Error fetching doctor information. Please try again.": "Error fetching doctor information. Please try again.",
    "Error fetching clinic information. Please try again.": "Error fetching clinic information. Please try again.",
    "Error fetching past consultations. Please try again.": "Error fetching past consultations. Please try again.",
    "Error processing timezone. Please try again.": "Error processing timezone. Please try again.",
    "You have no upcoming bookings.": "You have no upcoming bookings.",
    "Action Required": "Action Required",
    "Confirmed": "Confirmed",
    "Pending": "Pending",
    "Consultation with Dr. {} at {} on {} at {} (Symptoms: {})": "Consultation with Dr. {} at {} on {} at {} (Symptoms: {})",
    "Checkup ({}) with Dr. {} at {} on {} at {}": "Checkup ({}) with Dr. {} at {} on {} at {}",
    "Vaccination ({}) with Dr. {} at {} on {} at {}": "Vaccination ({}) with Dr. {} at {} on {} at {}",
    "Pending {} ({}) with Dr. {} at {} on {} at {}": "Pending {} ({}) with Dr. {} at {} on {} at {}",
    "{} ({}) with Dr. {} at {} on {} at {} (New: {} at {})": "{} ({}) with Dr. {} at {} on {} at {} (New: {} at {})",
    "Error fetching consultation bookings. Continuing with other bookings.": "Error fetching consultation bookings. Continuing with other bookings.",
    "Error fetching checkup bookings. Continuing with other bookings.": "Error fetching checkup bookings. Continuing with other bookings.",
    "Error fetching vaccination bookings. Continuing with other bookings.": "Error fetching vaccination bookings. Continuing with other bookings.",
    "Error fetching pending bookings. Continuing with other bookings.": "Error fetching pending bookings. Continuing with other bookings.",
    "Error fetching reschedule requests. Continuing with other bookings.": "Error fetching reschedule requests. Continuing with other bookings.",
    "Please select an option:": "Please select an option:",
    "Error displaying the booking menu. Please try again.": "Error displaying the booking menu. Please try again.",
    "An unexpected error occurred while fetching past consultations. Please try again.": "An unexpected error occurred while fetching past consultations. Please try again.",
    "An unexpected error occurred while fetching upcoming bookings. Please try again.": "An unexpected error occurred while fetching upcoming bookings. Please try again.",

    # From reschedule_booking.py - TITLES
    "Choose Category": "Choose Category",
    "Categories": "Categories",
    "Choose Booking": "Choose Booking",
    "Bookings": "Bookings",
    "Reschedule": "Reschedule",
    "Cancel Booking": "Cancel Booking",
    "Accept": "Accept",
    "Decline": "Decline",
    # CONTENT
    "You have no upcoming bookings to reschedule.": "You have no upcoming bookings to reschedule.",
    "Select a category to reschedule from:": "Select a category to reschedule from:",
    "Select a booking to manage:": "Select a booking to manage:",
    "Selected: {}": "Selected: {}",
    "Invalid category selection. Please try again.": "Invalid category selection. Please try again.",
    "No bookings available in {} category.": "No bookings available in {} category.",
    "Invalid booking selection. Please try again.": "Invalid booking selection. Please try again.",
    "You have accepted the reschedule. Your {} is now confirmed on {} at {}.": "You have accepted the reschedule. Your {} is now confirmed on {} at {}.",
    "You have declined the reschedule request.": "You have declined the reschedule request.",
    "Your booking has been cancelled.": "Your booking has been cancelled.",
    "Invalid booking ID format. Please try again.": "Invalid booking ID format. Please try again.",
    "Reschedule request not found or has invalid data. Please try again.": "Reschedule request not found or has invalid data. Please try again.",
    "Invalid booking type for reschedule request.": "Invalid booking type for reschedule request.",
    "Booking not found. It may have already been cancelled.": "Booking not found. It may have already been cancelled.",
    "✅ RESCHEDULED!\n\n{} moved to {} at {} with Dr. {} ({}min)\nStatus: PENDING APPROVAL": "✅ RESCHEDULED!\n\n{} moved to {} at {} with Dr. {} ({}min)\nStatus: PENDING APPROVAL",
    "Booking not found!": "Booking not found!",
    "Save error! Please try again.": "Save error! Please try again.",
    "An error occurred during rescheduling. Please try again.": "An error occurred during rescheduling. Please try again.",
    "Invalid input. Please try again.": "Invalid input. Please try again.",

    # From checkup_booking.py
    "Please select a checkup type:": "Please select a checkup type:",
    "Choose Checkup": "Choose Checkup",
    "Checkup Types": "Checkup Types",
    "Please specify the checkup type:": "Please specify the checkup type:",
    "Do you have any remarks for {} ({} min)?": "Do you have any remarks for {} ({} min)?",
    "Yes": "Yes",
    "No": "No",
    "Please enter your remarks:": "Please enter your remarks:",

    # From report_symptom.py
    "Please describe your symptoms.": "Please describe your symptoms.",

    # From vaccination.py
    "Please select a vaccine type:": "Please select a vaccine type:",
    "Choose Vaccine": "Choose Vaccine",
    "Vaccine Types": "Vaccine Types",
    "Please specify the vaccine type:": "Please specify the vaccine type:",

    # From report_booking.py
    "📋 Select Report": "📋 Select Report",
    "Select Report": "Select Report",
    "Your Reports": "Your Reports",
    "No pending reports found. Please book a checkup first.": "No pending reports found. Please book a checkup first.",
    "Choose a report to book review:": "Choose a report to book review:",
    "Bkng {}": "Bkng {}",
    "Error fetching reports. Please try again.": "Error fetching reports. Please try again.",
    "Error: No doctor found for this report. Contact support.": "Error: No doctor found for this report. Contact support.",
    "Error selecting report. Please try again.": "Error selecting report. Please try again.",
    "✅ Your report review booking is pending approval!": "✅ Your report review booking is pending approval!",
    "Error creating booking. Please try again.": "Error creating booking. Please try again.",
    "Please confirm your booking:\nReport: {}\nDoctor: {}\nDate: {}\nTime: {}\nDuration: {} min": "Please confirm your booking:\nReport: {}\nDoctor: {}\nDate: {}\nTime: {}\nDuration: {} min",
    "Choose a report to book review:\n{}": "Choose a report to book review:\n{}",
    "{} by {} in {}": "{} by {} in {}",
    "Your report PDF has been sent. Would you like to book a consultation to discuss the results?": "Your report PDF has been sent. Would you like to book a consultation to discuss the results?",
    "Failed to send PDF. Please try again later or book a consultation.": "Failed to send PDF. Please try again later or book a consultation.",
    "PDF report is not yet available. Would you like to book a consultation with the doctor?": "PDF report is not yet available. Would you like to book a consultation with the doctor?",
    "Your report PDF": "Your report PDF",
    "Back to Main Menu": "Back to Main Menu",
    "What would you like to do with this report?\n\n*{}*": "What would you like to do with this report?\n\n*{}*",
    "Request PDF": "Request PDF",
    "Consultation": "Consultation",
    "Your report review booking is pending approval by the admin.": "Your report review booking is pending approval by the admin.",
    "Error saving booking. Please try again.": "Error saving booking. Please try again.",
    "Please enter your preferred date as DD/MM/YYYY, DD-MM-YYYY or DD MM YYYY:": "Please enter your preferred date as DD/MM/YYYY, DD-MM-YYYY or DD MM YYYY:",
    
    # From post_report.py
    "Invalid selection. Please try again.": "Invalid selection. Please try again.",
    "Error processing your selection. Please try again.": "Error processing your selection. Please try again.",
    "Error fetching consultation details. Please try again.": "Error fetching consultation details. Please try again.",
    "Consultation not found or not associated with this number. Please try again.": "Consultation not found or not associated with this number. Please try again.",
    "Error generating report request. Please try again.": "Error generating report request. Please try again.",
    "Error processing report request. Please try again.": "Error processing report request. Please try again.",
    "Please enter the patient's IC in the format 'verified:<IC>', e.g., verified:123456789011": "Please enter the patient's IC in the format 'verified:<IC>', e.g., verified:123456789011",
    "An unexpected error occurred while processing your report request. Please try again.": "An unexpected error occurred while processing your report request. Please try again.",
    "IC verification failed. Please enter the correct patient IC.": "IC verification failed. Please enter the correct patient IC.",
    "No report request found. Please try again.": "No report request found. Please try again.",
    "Invalid report request status. Please try again.": "Invalid report request status. Please try again.",
    "Error processing verification. Please try again.": "Error processing verification. Please try again.",
    "IC verified, but error sending report. Please try again.": "IC verified, but error sending report. Please try again.",
    "IC verified, but the report is not yet available. You will be notified when ready.": "IC verified, but the report is not yet available. You will be notified when ready.",
    "IC verified successfully, but no report request pending. Please select a consultation.": "IC verified successfully, but no report request pending. Please select a consultation.",
    "Invalid verification format. Please use 'verified:<IC>'.": "Invalid verification format. Please use 'verified:<IC>'.",
    "A referral letter has been generated. Please contact your healthcare provider for details.": "A referral letter has been generated. Please contact your healthcare provider for details.",
    "No referral required.": "No referral required.",
    "IC verified. Report for consultation on {} (Diagnosis: {}):\n{}\n\n{}": "IC verified. Report for consultation on {} (Diagnosis: {}):\n{}\n\n{}",
    "Booking cancelled.": "Booking cancelled.",
}

# UPDATE: Added supabase=None argument to handle dynamic translation calls
def en_translate_template(text: str, supabase=None) -> str:
    """Return original English text (baseline)."""
    return EN_TO_EN.get(text, text)